[package]
name = "fps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev.package.bevy_rapier3d]
opt-level = 3

[dependencies]
bevy = "0.8.1"
bevy_rapier3d = "0.16.2"
bevy_mod_debugdump = "0.5"
